import "./globals.css";
import type { Metadata } from "next";
import RootProvider from "../lib/Provider";

export const metadata: Metadata = {
  title: "Painting Service Ltd",
  description: "Generated by create next app",
  icons: "/icon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RootProvider>
        <body>{children}</body>
      </RootProvider>
    </html>
  );
}
